export const images = {
  logo: require('./images/logo.png'),
  bwSolo: require('./images/bw-solo.png'),
  bwSoloPro: require('./images/bw-solo-pro.png'),
  coloredSolo: require('./images/colored-solo.png'),
  coloredSoloPro: require('./images/colored-solo-pro.png'),
  formCard: require('./images/formCard.png'),
  formBar: require('./images/formBar.png'),
  cardAddress: require('./images/cardWithAddress.png'),
  cardAddressBack: require('./images/cardWithAddressBack.png'),
  soloSimple: require('./images/Solosimple.png'),
  soloSimpleNumber2: require('./images/Number2.png'),
  soloSimpleNumber3: require('./images/Number3.png'),
  soloSimpleNumber4: require('./images/Number4.png'),
  nfcBlueIcon: require('./icons/nfc-blue-reader.png'),
  cpTransparentLogo: require('./images/CoinplusTransparentLogo.png'),
  authID: require('./images/authID.png'),
};
